### ISSUE TITLE
Failure to boot after upgrade from 1.26 to 1.27

### ISSUE THREAD

**Issue by tadgh** [linuxserver/docker-overseerr#12]
Hey all, using overseerr provided by linuxserver over [here](https://github.com/linuxserver/docker-overseerr/pkgs/container/overseerr). I am running in Docker on unraid. After an upgrade to 1.27.0 (published 9 hours ago) it fails to boot. If i completely remove my config folder and boot it fresh, its fine, it just seems to not be happy with the upgrade: 

```
1-02T13:21:59.517Z [[32minfo[39m]: Starting Overseerr version 1.27.0
2021-11-02T13:21:59.494Z [[32minfo[39m]: Commit Tag: v1.27.0
2021-11-02T13:21:59.517Z [[32minfo[39m]: Starting Overseerr version 1.27.0
2021-11-02T13:22:00.248Z [[31merror[39m]: TypeError: Cannot read property 'Directory' of undefined
at PlexAPI.getLibraries (/app/overseerr/dist/api/plexapi.js:46:40)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async PlexAPI.syncLibraries (/app/overseerr/dist/api/plexapi.js:50:27)
at async /app/overseerr/dist/index.js:82:13
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.10
$ NODE_ENV=production node dist/index.js
2021-11-02T13:22:02.496Z [[32minfo[39m]: Commit Tag: v1.27.0
2021-11-02T13:22:02.522Z [[32minfo[39m]: Starting Overseerr version 1.27.0
2021-11-02T13:22:03.306Z [[31merror[39m]: TypeError: Cannot read property 'Directory' of undefined
at PlexAPI.getLibraries (/app/overseerr/dist/api/plexapi.js:46:40)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async PlexAPI.syncLibraries (/app/overseerr/dist/api/plexapi.js:50:27)
at async /app/overseerr/dist/index.js:82:13
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```
The above repeats infinitely. 

Below is the result of me inspecting the docker container: 

```
[
    {
        "Id": "91ef40fdf69ccaf225c108c48b0552f50ff8d0d50c189c0198b331f69d5aa851",
        "Created": "2021-11-02T13:19:52.437184991Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 16231,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-11-02T13:24:11.064858325Z",
            "FinishedAt": "2021-11-02T13:23:52.660825599Z"
        },
        "Image": "sha256:f89b573af8a968adfc7bed61aee3723f0c4f1edc3f11261bf848db79eda1fd8e",
        "ResolvConfPath": "/var/lib/docker/containers/91ef40fdf69ccaf225c108c48b0552f50ff8d0d50c189c0198b331f69d5aa851/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/91ef40fdf69ccaf225c108c48b0552f50ff8d0d50c189c0198b331f69d5aa851/hostname",
        "HostsPath": "/var/lib/docker/containers/91ef40fdf69ccaf225c108c48b0552f50ff8d0d50c189c0198b331f69d5aa851/hosts",
        "LogPath": "/var/lib/docker/containers/91ef40fdf69ccaf225c108c48b0552f50ff8d0d50c189c0198b331f69d5aa851/91ef40fdf69ccaf225c108c48b0552f50ff8d0d50c189c0198b331f69d5aa851-json.log",
        "Name": "/overseerr",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt/user/appdata/overseerr:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "1",
                    "max-size": "50m"
                }
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "5055/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5055"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/user/appdata/overseerr",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "91ef40fdf69c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5055/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PUID=99",
                "PGID=100",
                "UMASK=022",
                "TZ=America/New_York",
                "HOST_OS=Unraid",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PS1=$(whoami)@$(hostname):$(pwd)\\$ ",
                "HOME=/config",
                "TERM=xterm"
            ],
            "Cmd": null,
            "Image": "lscr.io/linuxserver/overseerr",
            "Volumes": {
                "/config": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "build_version": "Linuxserver.io version:- v1.27.0-ls20 Build-date:- 2021-11-02T04:30:19+01:00",
                "maintainer": "nemchik",
                "org.opencontainers.image.authors": "linuxserver.io",
                "org.opencontainers.image.created": "2021-11-02T04:30:19+01:00",
                "org.opencontainers.image.description": "[Overseerr](https://overseerr.dev/) is a request management and media discovery tool built to work with your existing Plex ecosystem.  ",
                "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-overseerr",
                "org.opencontainers.image.licenses": "GPL-3.0-only",
                "org.opencontainers.image.ref.name": "75c6915bcb10d7c48c6d9b739ef4cfca6800c653",
                "org.opencontainers.image.revision": "75c6915bcb10d7c48c6d9b739ef4cfca6800c653",
                "org.opencontainers.image.source": "https://github.com/linuxserver/docker-overseerr",
                "org.opencontainers.image.title": "Overseerr",
                "org.opencontainers.image.url": "https://github.com/linuxserver/docker-overseerr/packages",
                "org.opencontainers.image.vendor": "linuxserver.io",
                "org.opencontainers.image.version": "v1.27.0-ls20"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "c69adb630d7d45c200234872c0231235bcd9e5b3e75adda31d644a743533e12f",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5055/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5055"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/c69adb630d7d",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "f93f61b727b3928dab4e96b600f9e6cef0f66c1871427935255c2785a61c6b48",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.5",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "00:00:00:00:00", #note i've replaced this
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "4715ed67653c5fb182280127d9d2e9b9fc0d948acd4b610774ec4f5705f1f15c",
                    "EndpointID": "f93f61b727b3928dab4e96b600f9e6cef0f66c1871427935255c2785a61c6b48",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.5",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:00:00:00:00", #note i've replaced this
                    "DriverOpts": null
                }
            }
        }
    }
]
```

The docker command used to boot it is: 
```
docker run -d --name='overseerr' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='022' -p '5055:5055/tcp' -v '/mnt/user/appdata/overseerr':'/config':'rw' 'lscr.io/linuxserver/
```

**Comment by TheCatLady** [comment]
sct/overseerr#2253

**Comment by tadgh** [comment]
Just want to validate that these errors should be treated the same: 
```
2021-11-01T19:50:25.150Z [�[31merror�[39m]: Error: Permission denied even after attempted authentication :( Wrong username and/or password maybe?
```
Versus what I am seeing which is: 
```
2021-11-02T13:22:00.248Z [�[31merror�[39m]: TypeError: Cannot read property 'Directory' of undefined
at PlexAPI.getLibraries (/app/overseerr/dist/api/plexapi.js:46:40)
```
Just different symptoms of the same problem I am guessing. Thanks!
